Creating docker build template
gohypergiant/.github pull request #6
Opened 2021-06-22 17:55 UTC by dineshgopagani

## Summary
Creating an action template for docker build image.

## Ticket(s)
- [EAIP-356](https://gohypergiant.atlassian.net/browse/EAIP-356)

2021-06-22 20:44 UTC, bbriggs requested changes
Use this for referenec
https://github.com/bytebot-chat/gateway-irc/blob/main/.github/workflows/docker_build.yaml

2021-06-22 22:06 UTC, dineshgopagani commented
> Use this for referenec
> https://github.com/bytebot-chat/gateway-irc/blob/main/.github/workflows/docker_build.yaml

Updated with Requested Changes. 
This template is to just build the docker images.

2021-06-23 02:00 UTC, bbriggs requested changes

2021-06-23 13:18 UTC, dineshgopagani commented on workflow-templates/docker-build-template.yml
> +      -
@bbriggs we don't need ECR login, as part of this template we are not pushing the image. We only need to verify if the docker image is build or not.

2021-06-23 14:23 UTC, dineshgopagani commented on workflow-templates/docker-build-template.yml
> +          images: dkr.fraq.dev/bytebot/gateway-irc
Updated.

2021-06-23 16:46 UTC, dineshgopagani commented on workflow-templates/docker-build-template.yml
> +      -
Added ECR login

2021-06-25 15:21 UTC, bbriggs requested changes
Update branch name then LGTM

2021-06-25 15:21 UTC, bbriggs commented on workflow-templates/docker-build-template.yml
> +      - 'main'
`stable` is the default branch at HG
```suggestion
      - 'stable'
```

2021-06-25 15:21 UTC, bbriggs commented on workflow-templates/docker-build-template.yml
> +      - 'main'
```suggestion
      - 'stable'
```

2021-06-27 23:58 UTC, dineshgopagani commented on workflow-templates/docker-build-template.yml
> +      - 'main'
Updated branch name to stable

2021-06-27 23:58 UTC, dineshgopagani commented on workflow-templates/docker-build-template.yml
> +      - 'main'
Updated branch name to stable

2021-06-28 20:42 UTC, bbriggs approved these changes

2021-06-28 20:54 UTC, merged